name: Run tests
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install poetry
        run: pip install poetry
      - name: checkout
        uses: actions/checkout@v2
      - name: insall dependencies
        run: poetry install
      - name: run tests
        run: poetry run pytest
      - name: build
        run: poetry build
      - name: upload artifacts
        uses: actions/upload-artifacts@v4
        path: dist/*.whl
    
