name: Run tests
on:
  push:
    tags: ["v*"]

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Install poetry
        run: pip install poetry
        
      - name: checkout
        uses: actions/checkout@v4
        
      - name: insall dependencies
        run: poetry install
        
      - name: run tests
        run: poetry run pytest
        
      - name: build
        run: poetry build
        
      - name: create release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create $TAG --title "Release $TAG" --generate-notes
      
      - name: upload release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: gh release upload $TAG ./dist/*.whl

